# Simple checks and deploy to GCP
name: Master Deploy on Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Check and Deploy
    runs-on: ubunntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Slack Notification
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author: Push Master CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: always()
